import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const ExamplePage: NextPage = () => {
  const router = useRouter();
  const { param } = router.query;
  return (
    <div>
      <Head>
        <title>ExamplePage</title>
        <meta name="description" content="Generated by exequiroga.dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{param}</div>
    </div>
  );
};

export default ExamplePage;
