import {
  NextPage,
} from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Home page</title>
      <meta name="description" content="Generated by exequiroga.dev" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>Hello Next.js</h1>
  </div>
);

export default Home;
