import { NextPage } from 'next';
import Head from 'next/head';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';

const now = format(new Date(), 'PPPppp', { locale: es });

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Home page</title>
      <meta name="description" content="Generated by exequiroga.dev" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>{`Hoy es ${now}`}</h1>
  </div>
);

export default Home;
